// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkiyemxodtbpzyvuxdgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRraXllbXhvZHRicHp5dnV4ZGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTg4NTksImV4cCI6MjA1ODAzNDg1OX0.jkLH9rFhXnNG41MiPHXdM3zmwFF5GZWchPj1lorcOh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);